In [275]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

import pickle

In [43]:
car = pd.read_csv('quikr_car.csv')
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [44]:
car.shape

(892, 6)

## Analyse Data

- Column names are pretty inconsistent
- Coulmn names have company names attached to it
- Some names are spam like 'Maruti Ertiga showroom condition with' and 'Well mentained Tata Sumo'
- company: many of the names are not of any company like 'Used', 'URJENT', and so on.
- Column year has many non-year values
- Column year is in object. Change to integer
- Price has the  value  'Ask for Price'
- Price has commas in its prices and is in object
- Column kms_driven has object values with kms at last.
- It has nan values and two rows have 'Petrol' in them
- Column fuel_type has nan values

In [45]:
car.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        892 non-null    str
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 92.3 KB

In [46]:
# Date is in str format
car['year'].unique()

<ArrowStringArray>
['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016', '2010',
 '2017', '2008', '2011', '2019', '2009', '2005', '2000',  '...', '150k',
 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs', 'sale', '1995', 'ara)',
 '2002', 'SELL', '2001', 'tion', 'odel', '2 bs', 'arry',  'Eon', 'o...',
 'ture',  'emi',  'car', 'able',  'no.', 'd...', 'SALE', 'digo', 'sell',
 'd Ex', 'n...', 'e...', 'D...', ', Ac', 'go .', 'k...', 'o c4', 'zire',
 'cent', 'Sumo',  'cab', 't xe',  'EV2', 'r...', 'zest']
Length: 61, dtype: str

In [47]:
# Price is in string 
car['Price'].values

<ArrowStringArray>
[       '80,000',      '4,25,000', 'Ask For Price',      '3,25,000',
      '5,75,000', 'Ask For Price',      '1,75,000',      '1,90,000',
      '8,30,000',      '2,50,000',
 ...
 'Ask For Price',      '2,70,000',      '4,50,000',      '1,10,000',
      '3,00,000',      '3,10,000',      '2,60,000',      '3,90,000',
      '1,80,000',      '1,60,000']
Length: 892, dtype: str

In [48]:
car['kms_driven'].values

<ArrowStringArray>
[  '45,000 kms',       '40 kms',   '22,000 kms',   '28,000 kms',
   '36,000 kms',   '59,000 kms',   '41,000 kms',   '25,000 kms',
   '24,530 kms',   '60,000 kms',
 ...
   '70,000 kms',   '50,000 kms',            nan,   '30,000 kms',
 '1,32,000 kms',            nan,   '27,000 kms',   '40,000 kms',
       'Petrol',       'Petrol']
Length: 892, dtype: str

In [49]:
# Check for null values
car.isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [50]:
car[car['kms_driven'].isnull() == True]

,name,company,year,Price,kms_driven,fuel_type
69,I want to sell my car Tata Zest,I,2017,Ask For Price,NaN,NaN
85,I want to sell my car Tata Zest,I,2017,Ask For Price,NaN,NaN
185,"Commercial , DZire LDI, 2016, for sale",Commercial,...,Ask For Price,NaN,NaN
195,"Tata indigo ecs LX, 201",Tata,150k,"1,50,000",NaN,NaN
206,MARUTI SUZUKI DESI,MARUTI,TOUR,"4,00,000",NaN,NaN
286,"Commercial , DZire LDI, 2016, for sale",Commercial,...,Ask For Price,NaN,NaN
294,Yama,Yamaha,r 15,"55,000",NaN,NaN
360,selling car Ta,selling,Zest,Ask For Price,NaN,NaN
368,Tata Zest 90,Tata,/-Rs,Ask For Price,NaN,NaN
385,Maruti Suzuki Swift Dzire car,Maruti,sale,"3,00,000",NaN,NaN
395,Maruti Suzuki Swift Dzire Tour (Gat,Maruti,ara),"3,00,000",NaN,NaN
401,URJE,URJENT,SELL,"1,80,000",NaN,NaN
414,Swift Dzire Tour 27 Dec 2016 Regis,Swift,tion,"3,70,000",NaN,NaN
432,Tata zest x,Tata,odel,"3,20,000",NaN,NaN
433,Mahindra xyl,Mahindra,2 bs,"3,50,000",NaN,NaN
441,Used Commercial Maruti Omn,Used,arry,"1,50,000",NaN,NaN
560,Hyun,Hyundai,Eon,Ask For Price,NaN,NaN
593,Commercial Chevrolet Sail Hatchback ca,Commercial,o...,"2,25,000",NaN,NaN
599,Commercial Car Ta,Commercial,Zest,"3,71,500",NaN,NaN
608,tata Indica,tata,sale,"1,30,000",NaN,NaN
614,Used bt new conditions ta,Used,Zest,"2,55,000",NaN,NaN
616,Sale tata,Sale,ture,"1,00,000",NaN,NaN
624,Tata indigo 2017 top model..,Tata,emi,"1,70,000",NaN,NaN
635,Tata indigo,Tata,car,"1,50,000",NaN,NaN
643,very good condition tata bolts are av,very,able,"2,00,000",NaN,NaN
645,Sale Hyundai xcent commerc,Sale,no.,Ask For Price,NaN,NaN
723,I want to sell my commercial car due t,I,o...,"4,75,000",NaN,NaN
725,i want sale my car.no emi....uber atta,i,d...,"3,20,000",NaN,NaN
728,Tata ZEST 6 month old,Tata,car,"3,70,000",NaN,NaN
758,MARUTI SUZUKI ERTIGA F,MARUTI,SALE,"6,50,000",NaN,NaN
764,Tata,Tata,digo,Ask For Price,NaN,NaN
792,2012 Tata Sumo Gold f,2012,sell,"2,50,000",NaN,NaN
795,Well mentained Tata Sumo,Well,d Ex,"3,80,000",NaN,NaN
796,all paper updated tata indica v2 and u,all,n...,"1,45,000",NaN,NaN
797,Maruti Ertiga showroom condition with,Maruti,e...,"4,80,000",NaN,NaN
798,7 SEATER MAHINDRA BOLERO IN VERY GOOD,7,D...,Ask For Price,NaN,NaN
799,9 SEATER MAHINDRA BOL,9,", Ac",Ask For Price,NaN,NaN
800,scratch less Tata I,scratch,go .,"1,40,000",NaN,NaN
801,Maruti Suzuki swift dzire for sale in,Maruti,d...,"3,60,000",NaN,NaN
802,Commercial Chevrolet beat for sale in,Commercial,k...,"1,80,000",NaN,NaN
803,urgent sell my Mahindra qu,urgent,o c4,"3,50,000",NaN,NaN
805,sell my car Maruti Suzuki Swif,sell,zire,"3,00,000",NaN,NaN
806,Maruti Suzuki Swift Dzire good car fo,Maruti,o...,"3,10,000",NaN,NaN
807,Hyunda,Hyundai,cent,Ask For Price,NaN,NaN
808,Commercial Maruti Suzuki Alto Lxi 800,Commercial,...,Ask For Price,NaN,NaN
809,urgent sale Ta,urgent,Sumo,"2,20,000",NaN,NaN
810,Maruti Suzuki Alto vxi t,Maruti,cab,"95,000",NaN,NaN
811,tata,tata,t xe,Ask For Price,NaN,NaN
812,TATA INDI,TATA,EV2,"1,10,000",NaN,NaN
845,Any type car avaiabel hare...comercica,Any,r...,"1,70,000",NaN,NaN
884,tata zest 2017 f,tata,sale,"4,50,000",NaN,NaN
887,Ta,Tara,zest,"3,10,000",NaN,NaN

In [51]:
car['name']

0        Hyundai Santro Xing XO eRLX Euro III
1                     Mahindra Jeep CL550 MDI
2                  Maruti Suzuki Alto 800 Vxi
3      Hyundai Grand i10 Magna 1.2 Kappa VTVT
4            Ford EcoSport Titanium 1.5L TDCi
                        ...
887                                        Ta
888                       Tata Zest XM Diesel
889                        Mahindra Quanto C8
890                  Honda Amaze 1.2 E i VTEC
891                 Chevrolet Sail 1.2 LT ABS
Name: name, Length: 892, dtype: str

## Data Cleaning

In [173]:
df = car.copy()

In [174]:
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [175]:
df[df['year'].str.isnumeric()]

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [176]:
df[df['year'].str.isnumeric()].shape

(842, 6)

In [177]:
df[df['year'].str.isnumeric() == False]

,name,company,year,Price,kms_driven,fuel_type
185,"Commercial , DZire LDI, 2016, for sale",Commercial,...,Ask For Price,NaN,NaN
195,"Tata indigo ecs LX, 201",Tata,150k,"1,50,000",NaN,NaN
206,MARUTI SUZUKI DESI,MARUTI,TOUR,"4,00,000",NaN,NaN
286,"Commercial , DZire LDI, 2016, for sale",Commercial,...,Ask For Price,NaN,NaN
294,Yama,Yamaha,r 15,"55,000",NaN,NaN
360,selling car Ta,selling,Zest,Ask For Price,NaN,NaN
368,Tata Zest 90,Tata,/-Rs,Ask For Price,NaN,NaN
385,Maruti Suzuki Swift Dzire car,Maruti,sale,"3,00,000",NaN,NaN
395,Maruti Suzuki Swift Dzire Tour (Gat,Maruti,ara),"3,00,000",NaN,NaN
401,URJE,URJENT,SELL,"1,80,000",NaN,NaN
414,Swift Dzire Tour 27 Dec 2016 Regis,Swift,tion,"3,70,000",NaN,NaN
432,Tata zest x,Tata,odel,"3,20,000",NaN,NaN
433,Mahindra xyl,Mahindra,2 bs,"3,50,000",NaN,NaN
441,Used Commercial Maruti Omn,Used,arry,"1,50,000",NaN,NaN
560,Hyun,Hyundai,Eon,Ask For Price,NaN,NaN
593,Commercial Chevrolet Sail Hatchback ca,Commercial,o...,"2,25,000",NaN,NaN
599,Commercial Car Ta,Commercial,Zest,"3,71,500",NaN,NaN
608,tata Indica,tata,sale,"1,30,000",NaN,NaN
614,Used bt new conditions ta,Used,Zest,"2,55,000",NaN,NaN
616,Sale tata,Sale,ture,"1,00,000",NaN,NaN
624,Tata indigo 2017 top model..,Tata,emi,"1,70,000",NaN,NaN
635,Tata indigo,Tata,car,"1,50,000",NaN,NaN
643,very good condition tata bolts are av,very,able,"2,00,000",NaN,NaN
645,Sale Hyundai xcent commerc,Sale,no.,Ask For Price,NaN,NaN
723,I want to sell my commercial car due t,I,o...,"4,75,000",NaN,NaN
725,i want sale my car.no emi....uber atta,i,d...,"3,20,000",NaN,NaN
728,Tata ZEST 6 month old,Tata,car,"3,70,000",NaN,NaN
758,MARUTI SUZUKI ERTIGA F,MARUTI,SALE,"6,50,000",NaN,NaN
764,Tata,Tata,digo,Ask For Price,NaN,NaN
792,2012 Tata Sumo Gold f,2012,sell,"2,50,000",NaN,NaN
795,Well mentained Tata Sumo,Well,d Ex,"3,80,000",NaN,NaN
796,all paper updated tata indica v2 and u,all,n...,"1,45,000",NaN,NaN
797,Maruti Ertiga showroom condition with,Maruti,e...,"4,80,000",NaN,NaN
798,7 SEATER MAHINDRA BOLERO IN VERY GOOD,7,D...,Ask For Price,NaN,NaN
799,9 SEATER MAHINDRA BOL,9,", Ac",Ask For Price,NaN,NaN
800,scratch less Tata I,scratch,go .,"1,40,000",NaN,NaN
801,Maruti Suzuki swift dzire for sale in,Maruti,d...,"3,60,000",NaN,NaN
802,Commercial Chevrolet beat for sale in,Commercial,k...,"1,80,000",NaN,NaN
803,urgent sell my Mahindra qu,urgent,o c4,"3,50,000",NaN,NaN
805,sell my car Maruti Suzuki Swif,sell,zire,"3,00,000",NaN,NaN
806,Maruti Suzuki Swift Dzire good car fo,Maruti,o...,"3,10,000",NaN,NaN
807,Hyunda,Hyundai,cent,Ask For Price,NaN,NaN
808,Commercial Maruti Suzuki Alto Lxi 800,Commercial,...,Ask For Price,NaN,NaN
809,urgent sale Ta,urgent,Sumo,"2,20,000",NaN,NaN
810,Maruti Suzuki Alto vxi t,Maruti,cab,"95,000",NaN,NaN
811,tata,tata,t xe,Ask For Price,NaN,NaN
812,TATA INDI,TATA,EV2,"1,10,000",NaN,NaN
845,Any type car avaiabel hare...comercica,Any,r...,"1,70,000",NaN,NaN
884,tata zest 2017 f,tata,sale,"4,50,000",NaN,NaN
887,Ta,Tara,zest,"3,10,000",NaN,NaN

In [178]:
df[df['year'].str.isnumeric() == False].shape

(50, 6)

#### Remove rows where year is non-numeric

In [179]:
df = df[df['year'].str.isnumeric()]
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

#### Change the datatype of year column to int

In [180]:
df['year'] = df['year'].astype(int)
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [181]:
df.info()

<class 'pandas.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    str
 1   company     842 non-null    str
 2   year        842 non-null    int64
 3   Price       842 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: int64(1), str(5)
memory usage: 91.4 KB

### Remove rows where price is non-numeric

In [182]:
df[df['Price'].str.isnumeric() == True]

Empty DataFrame
Columns: [name, company, year, Price, kms_driven, fuel_type]
Index: []

In [183]:
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [184]:
df = df[df['Price']!="Ask For Price"]
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
6,Ford Figo,Ford,2012,"1,75,000","41,000 kms",Diesel

In [185]:
df[df['Price'].str.isnumeric() == "Ask For Price"]

Empty DataFrame
Columns: [name, company, year, Price, kms_driven, fuel_type]
Index: []

In [186]:
df['Price'].replace(',','')

0        80,000
1      4,25,000
3      3,25,000
4      5,75,000
6      1,75,000
         ...
886    3,00,000
888    2,60,000
889    3,90,000
890    1,80,000
891    1,60,000
Name: Price, Length: 819, dtype: str

In [187]:
df['Price'] = df['Price'].str.replace(',','')

In [188]:
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,"45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40 kms,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,"28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,"36,000 kms",Diesel
6,Ford Figo,Ford,2012,175000,"41,000 kms",Diesel

In [189]:
df['Price'] = df['Price'].astype(int)
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,"45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40 kms,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,"28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,"36,000 kms",Diesel
6,Ford Figo,Ford,2012,175000,"41,000 kms",Diesel

In [190]:
df.info()

<class 'pandas.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    str
 1   company     819 non-null    str
 2   year        819 non-null    int64
 3   Price       819 non-null    int64
 4   kms_driven  819 non-null    str
 5   fuel_type   816 non-null    str
dtypes: int64(2), str(4)
memory usage: 82.4 KB

###  Analyse kms_driven

In [191]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,"45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40 kms,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,"28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,"36,000 kms",Diesel
6,Ford Figo,Ford,2012,175000,"41,000 kms",Diesel
...,...,...,...,...,...,...
886,Toyota Corolla Altis,Toyota,2009,300000,"1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,260000,"27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000,"40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,180000,Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,160000,Petrol,NaN

In [192]:
df.shape

(819, 6)

In [193]:
df[df['kms_driven'].str.isnumeric() == True]

Empty DataFrame
Columns: [name, company, year, Price, kms_driven, fuel_type]
Index: []

In [194]:
df['kms_driven'].unique()

<ArrowStringArray>
[  '45,000 kms',       '40 kms',   '28,000 kms',   '36,000 kms',
   '41,000 kms',   '25,000 kms',   '24,530 kms',   '60,000 kms',
   '30,000 kms',   '32,000 kms',
 ...
   '33,400 kms',   '60,123 kms', '1,37,495 kms',   '91,200 kms',
 '1,46,000 kms', '1,00,800 kms',    '2,100 kms',    '2,500 kms',
 '1,32,000 kms',       'Petrol']
Length: 250, dtype: str

In [195]:
df['kms_driven'].str.split()[0][0].replace(',','')

'45000'

In [196]:
df['kms_driven']= df['kms_driven'].str.split().str.get(0).str.replace(',','')

In [197]:
df['kms_driven'].unique()

array(['45000', '40', '28000', '36000', '41000', '25000', '24530',
       '60000', '30000', '32000', '48660', '4000', '16934', '43000',
       '35550', '39522', '39000', '55000', '72000', '15975', '70000',
       '23452', '35522', '48508', '15487', '82000', '20000', '68000',
       '38000', '27000', '33000', '46000', '16000', '47000', '35000',
       '30874', '15000', '29685', '130000', '19000', '54000', '13000',
       '38200', '22000', '50000', '13500', '3600', '45863', '60500',
       '12500', '18000', '13349', '29000', '44000', '42000', '14000',
       '49000', '36200', '51000', '104000', '33333', '33600', '5600',
       '7500', '26000', '24330', '65480', '200000', '59000', '99000',
       '2800', '21000', '11000', '66000', '3000', '7000', '38500',
       '37200', '43200', '24800', '45872', '40000', '11400', '97200',
       '52000', '31000', '175430', '37000', '65000', '3350', '75000',
       '62000', '73000', '2200', '54870', '34580', '97000', '60', '80200',
       '3200', '0000', '5000', '588', '71200', '175400', '9300', '56758',
       '10000', '56450', '56000', '32700', '9000', '73', '160000',
       '58559', '57000', '170000', '80000', '6821', '23000', '34000',
       '1800', '400000', '48000', '90000', '12000', '69900', '166000',
       '122', '0', '36469', '7800', '24695', '15141', '59910', '100000',
       '4500', '129000', '300', '131000', '111111', '59466', '25500',
       '44005', '2110', '43222', '100200', '65', '140000', '103553',
       '58000', '120000', '49800', '100', '81876', '6020', '55700',
       '18500', '53000', '35500', '22134', '1000', '8500', '87000',
       '6000', '8000', '55800', '56400', '72160', '11500', '133000',
       '2000', '88000', '65422', '117000', '150000', '10750', '6800',
       '9800', '57923', '30201', '6200', '37518', '24652', '383', '95000',
       '3528', '52500', '47900', '52800', '195000', '48008', '48247',
       '9400', '64000', '2137', '10544', '147000', '90001', '48006',
       '74000', '85000', '29500', '39700', '67000', '19336', '60105',
       '45933', '102563', '28600', '41800', '116000', '42590', '7400',
       '54500', '76000', '00', '11523', '38600', '95500', '37458',
       '85960', '12516', '30600', '2550', '62500', '69000', '28400',
       '68485', '3500', '85455', '63000', '1600', '77000', '26500',
       '2875', '13900', '1500', '2450', '1625', '33400', '60123',
       '137495', '91200', '146000', '100800', '2100', '2500', '132000',
       'Petrol'], dtype=object)

In [198]:
df.shape

(819, 6)

In [199]:
df = df[df['kms_driven']!='Petrol']

In [200]:
df.shape

(817, 6)

In [201]:
df['kms_driven'].unique()

array(['45000', '40', '28000', '36000', '41000', '25000', '24530',
       '60000', '30000', '32000', '48660', '4000', '16934', '43000',
       '35550', '39522', '39000', '55000', '72000', '15975', '70000',
       '23452', '35522', '48508', '15487', '82000', '20000', '68000',
       '38000', '27000', '33000', '46000', '16000', '47000', '35000',
       '30874', '15000', '29685', '130000', '19000', '54000', '13000',
       '38200', '22000', '50000', '13500', '3600', '45863', '60500',
       '12500', '18000', '13349', '29000', '44000', '42000', '14000',
       '49000', '36200', '51000', '104000', '33333', '33600', '5600',
       '7500', '26000', '24330', '65480', '200000', '59000', '99000',
       '2800', '21000', '11000', '66000', '3000', '7000', '38500',
       '37200', '43200', '24800', '45872', '40000', '11400', '97200',
       '52000', '31000', '175430', '37000', '65000', '3350', '75000',
       '62000', '73000', '2200', '54870', '34580', '97000', '60', '80200',
       '3200', '0000', '5000', '588', '71200', '175400', '9300', '56758',
       '10000', '56450', '56000', '32700', '9000', '73', '160000',
       '58559', '57000', '170000', '80000', '6821', '23000', '34000',
       '1800', '400000', '48000', '90000', '12000', '69900', '166000',
       '122', '0', '36469', '7800', '24695', '15141', '59910', '100000',
       '4500', '129000', '300', '131000', '111111', '59466', '25500',
       '44005', '2110', '43222', '100200', '65', '140000', '103553',
       '58000', '120000', '49800', '100', '81876', '6020', '55700',
       '18500', '53000', '35500', '22134', '1000', '8500', '87000',
       '6000', '8000', '55800', '56400', '72160', '11500', '133000',
       '2000', '88000', '65422', '117000', '150000', '10750', '6800',
       '9800', '57923', '30201', '6200', '37518', '24652', '383', '95000',
       '3528', '52500', '47900', '52800', '195000', '48008', '48247',
       '9400', '64000', '2137', '10544', '147000', '90001', '48006',
       '74000', '85000', '29500', '39700', '67000', '19336', '60105',
       '45933', '102563', '28600', '41800', '116000', '42590', '7400',
       '54500', '76000', '00', '11523', '38600', '95500', '37458',
       '85960', '12516', '30600', '2550', '62500', '69000', '28400',
       '68485', '3500', '85455', '63000', '1600', '77000', '26500',
       '2875', '13900', '1500', '2450', '1625', '33400', '60123',
       '137495', '91200', '146000', '100800', '2100', '2500', '132000'],
      dtype=object)

In [202]:
df['kms_driven'] = df['kms_driven'].astype(int)
df['kms_driven']

0       45000
1          40
3       28000
4       36000
6       41000
        ...
883     50000
885     30000
886    132000
888     27000
889     40000
Name: kms_driven, Length: 817, dtype: int64

In [203]:
df.info()

<class 'pandas.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    str
 1   company     817 non-null    str
 2   year        817 non-null    int64
 3   Price       817 non-null    int64
 4   kms_driven  817 non-null    int64
 5   fuel_type   816 non-null    str
dtypes: int64(3), str(3)
memory usage: 74.2 KB

### Column fuel_type has nan values

In [204]:
df.isnull().sum()

name          0
company       0
year          0
Price         0
kms_driven    0
fuel_type     1
dtype: int64

In [205]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
888,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [206]:
df[df['fuel_type'].isna()]

               name company  year   Price  kms_driven fuel_type
132  Toyota Corolla  Toyota  2009  275000       26000       NaN

In [207]:
df['fuel_type'].unique()

<ArrowStringArray>
['Petrol', 'Diesel', nan, 'LPG']
Length: 4, dtype: str

In [208]:
df = df[~df['fuel_type'].isna()]
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
888,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [209]:
df[df['fuel_type'].isna()]

Empty DataFrame
Columns: [name, company, year, Price, kms_driven, fuel_type]
Index: []

In [210]:
df.info()

<class 'pandas.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    str
 1   company     816 non-null    str
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    str
dtypes: int64(3), str(3)
memory usage: 74.1 KB

### Keep the first words of a name

In [211]:
df['name']

0        Hyundai Santro Xing XO eRLX Euro III
1                     Mahindra Jeep CL550 MDI
3      Hyundai Grand i10 Magna 1.2 Kappa VTVT
4            Ford EcoSport Titanium 1.5L TDCi
6                                   Ford Figo
                        ...
883                Maruti Suzuki Ritz VXI ABS
885                 Tata Indica V2 DLE BS III
886                      Toyota Corolla Altis
888                       Tata Zest XM Diesel
889                        Mahindra Quanto C8
Name: name, Length: 816, dtype: str

In [212]:
df['name'] = df['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [213]:
df

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Tata Indica V2      Tata  2009  110000       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Tata Zest XM      Tata  2018  260000       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [214]:
df.info()

<class 'pandas.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    str
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    str
dtypes: int64(3), object(1), str(2)
memory usage: 54.6+ KB

In [215]:
df.reset_index(drop=True)
df

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Tata Indica V2      Tata  2009  110000       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Tata Zest XM      Tata  2018  260000       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [216]:
df.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [218]:
df[df['Price']>6e6]

                   name   company  year    Price  kms_driven fuel_type
562  Mahindra XUV500 W6  Mahindra  2014  8500003       45000    Diesel

In [219]:
df = df[df['Price'] < 6e6]

In [220]:
df.describe()

              year         Price     kms_driven
count   815.000000  8.150000e+02     815.000000
mean   2012.442945  4.017933e+05   46277.096933
std       4.005079  3.815888e+05   34318.459638
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.900000e+05   56879.000000
max    2019.000000  3.100000e+06  400000.000000

In [221]:
df.shape

(815, 6)

In [223]:
df = df.reset_index(drop=True)
df

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [230]:
df

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [231]:
df.to_csv('cleaned_car.csv',index=False)

## Model Building

In [232]:
cleaned_car = pd.read_csv('cleaned_car.csv')
cleaned_car.head()

                     name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4               Ford Figo      Ford  2012  175000       41000    Diesel

In [233]:
cleaned_car.info()

<class 'pandas.DataFrame'>
RangeIndex: 815 entries, 0 to 814
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        815 non-null    str
 1   company     815 non-null    str
 2   year        815 non-null    int64
 3   Price       815 non-null    int64
 4   kms_driven  815 non-null    int64
 5   fuel_type   815 non-null    str
dtypes: int64(3), str(3)
memory usage: 61.7 KB

In [234]:
cleaned_car.shape

(815, 6)

In [236]:
X = cleaned_car.drop(columns='Price')
X.shape

(815, 5)

In [237]:
X.head()

                     name   company  year  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2       Hyundai Grand i10   Hyundai  2014       28000    Petrol
3  Ford EcoSport Titanium      Ford  2014       36000    Diesel
4               Ford Figo      Ford  2012       41000    Diesel

In [238]:
y = cleaned_car['Price']

In [239]:
y.shape

(815,)

### Creating an OneHotEncoder object to contain all the possible categories

In [245]:
one = OneHotEncoder()
one.fit(X[['name','company','fuel_type']])

OneHotEncoder()

In [246]:
X

                       name   company  year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2         Hyundai Grand i10   Hyundai  2014       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014       36000    Diesel
4                 Ford Figo      Ford  2012       41000    Diesel
..                      ...       ...   ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
811          Tata Indica V2      Tata  2009       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009      132000    Petrol
813            Tata Zest XM      Tata  2018       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 5 columns]

## Train Test Split

In [247]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

### Creating a column transformer to transform categorical columns

In [251]:
column_trans_df = make_column_transformer((OneHotEncoder(categories=one.categories_),['name','company','fuel_type']),
                                    remainder='passthrough')

In [252]:
column_trans_df

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat Diesel',
       'Chevrolet Beat LS', 'Chevrolet B...
       'Volkswagen Vento Konekt', 'Volvo S80 Summum'], dtype=object),
                                                           array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                           array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                 ['name', 'company', 'fuel_type'])])

## Linear Regression Model

In [253]:
lr=LinearRegression()

## Making the pipeline

In [255]:
pipe=make_pipeline(column_trans_df,lr)

## Fit the model

In [259]:
X_train

                          name     company  year  kms_driven fuel_type
284         Mahindra TUV300 T4    Mahindra  2016        9000    Diesel
576               Tata Zest XE        Tata  2017       70000    Diesel
220    Mitsubishi Pajero Sport  Mitsubishi  2015       47000    Diesel
58                   Ford Figo        Ford  2012       41000    Diesel
762       Mahindra Scorpio VLX    Mahindra  2014       77000    Diesel
..                         ...         ...   ...         ...       ...
417  Volkswagen Vento Highline  Volkswagen  2015       34000    Diesel
130           Hyundai i20 Asta     Hyundai  2009       65480    Petrol
526             Tata Indica V2        Tata  2005      150000    Diesel
217        Maruti Suzuki Wagon      Maruti  2006       71200    Petrol
326         Hyundai Elantra SX     Hyundai  2013       20000    Petrol

[652 rows x 5 columns]

In [256]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [257]:
y_pred=pipe.predict(X_test)
y_pred

array([ 2.13226989e+05,  5.03448369e+05,  4.41074415e+05,  1.46019259e+05,
        4.32929946e+05,  2.25507823e+05,  2.42482166e+05,  1.27310901e+05,
        1.59565144e+05,  9.82583223e+05,  2.10487198e+06,  3.57346876e+05,
        4.45962145e+05,  2.74742999e+05,  2.10487198e+06,  6.31844920e+04,
        5.85709999e+05,  2.38264353e+05,  5.32006195e+05,  2.74692691e+05,
        2.12985495e+05, -1.52700131e+03,  3.79159755e+05,  2.91414325e+05,
        4.84138354e+05,  1.57157047e+06,  5.43855080e+05,  4.75537426e+05,
        1.55441143e+05,  8.28767690e+05,  5.36563015e+05,  2.97943527e+05,
        3.99589176e+05,  9.20787563e+04,  3.53455927e+05,  3.75558679e+05,
        5.83689110e+05,  7.81022944e+05,  6.55497696e+05,  2.10487198e+06,
        2.80637505e+05,  2.88102336e+05,  5.42328088e+05,  3.57997188e+05,
        2.78104094e+05,  2.63638959e+05,  3.58263221e+05,  5.64800143e+05,
        3.98367917e+05,  1.67339847e+05,  1.14231401e+05,  2.89763735e+05,
        4.00289076e+05,  3.74201427e+05,  1.69622295e+05,  3.65877195e+05,
        4.78958872e+05,  2.58064243e+05,  1.94014701e+05,  1.90935341e+05,
        4.47802525e+05,  1.14194629e+05,  9.50139700e+05,  2.20441002e+05,
        2.15160645e+05,  3.80045283e+05,  6.04632968e+05,  2.77564869e+05,
        1.39908221e+05,  4.52385244e+05,  2.12084271e+05,  7.08290094e+05,
        3.79361741e+05,  4.79520464e+05,  7.54140841e+05,  3.89140647e+05,
        2.40771793e+05,  3.74918574e+05,  1.81918074e+05,  6.37705760e+05,
        6.11044502e+05,  1.84747146e+05,  9.09034628e+04,  3.10316569e+05,
        3.12633659e+05,  2.43750250e+04,  3.14481365e+04,  1.55476072e+05,
        3.70315212e+05,  6.38691290e+05,  2.84094358e+05,  3.05652827e+05,
        2.16603368e+05,  2.73956113e+05,  2.68823418e+05,  6.31844920e+04,
        4.58041906e+05,  3.26057264e+05,  4.18772338e+05,  1.36751316e+05,
        6.38691290e+05,  2.88841097e+05,  3.38101019e+05,  5.89610169e+05,
        2.10487198e+06,  2.12084271e+05,  4.69830722e+05,  6.11044502e+05,
        1.26820813e+05,  5.33632847e+05,  2.95101820e+05,  3.01974245e+05,
        3.65863721e+05,  8.28767690e+05,  4.72283057e+05,  4.12000585e+05,
        5.45730406e+05,  6.40051475e+05,  5.30859719e+05,  4.06321425e+05,
        4.32929946e+05,  2.10409947e+05,  2.94692104e+05,  3.01817774e+05,
        3.01644849e+05,  2.47650652e+05,  5.27847365e+05,  2.32077075e+04,
        2.59941125e+05,  4.28123133e+05,  1.39762214e+05,  2.53276728e+05,
        2.97476992e+05,  4.93470748e+05,  6.98892542e+05,  3.50545259e+05,
        6.25402421e+05,  1.90206937e+05,  2.57862392e+05,  4.60684833e+05,
        1.09157721e+06,  2.40771793e+05,  4.37986067e+05,  1.58067297e+06,
        6.61411299e+05,  2.62807320e+05,  1.11674568e+06,  4.30209462e+05,
        9.60012902e+05,  2.85670756e+05,  3.70008824e+05,  5.45730406e+05,
       -1.82669824e+04,  4.73137028e+05,  5.52553019e+05,  1.53908437e+05,
        1.03368081e+05,  1.19139157e+05,  8.28767690e+05,  3.11211314e+05,
        5.08703173e+05,  2.64993347e+05,  5.77993658e+05])

## R2 Score

In [258]:
r2_score(y_test,y_pred)

0.7730379478037811

## Finding the model with a random state of TrainTestSplit

In [261]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans_df,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    scores.append(r2_score(y_test,y_pred))

In [274]:
scores

[0.6397463008458546,
 0.5706879360249344,
 0.612098980488621,
 0.4752543857047593,
 0.7936421853019084,
 0.6042633012489798,
 0.44467830770956707,
 0.520440352136609,
 0.5444996120697918,
 0.6456144411163149,
 0.6669250041040315,
 0.6570062380453807,
 0.460277872148802,
 0.596971885820896,
 0.7322000999333089,
 0.5987204596627098,
 0.46927750194781215,
 0.6711937258879767,
 0.574866325439801,
 0.7054447025079494,
 0.7178337175837914,
 0.38738858286768396,
 0.64997557370579,
 0.5751950980948098,
 0.4576315364115008,
 0.48396541097321755,
 0.7341302636690202,
 0.7364381460664248,
 0.6977475430796969,
 0.5961264025422347,
 0.6767513370954059,
 0.8447005387339755,
 0.7439893057799531,
 0.8008878465814028,
 0.6369469817245492,
 0.7979261874242201,
 0.5052836582371808,
 0.48555019223462403,
 0.4879367558173847,
 0.7621644541218072,
 0.4230333104998736,
 0.6947697494074163,
 0.4849789902118432,
 0.5153270858289933,
 0.6071200861216044,
 0.7118453496750381,
 0.47063273654777793,
 0.4720808867234533,
 0.7680566479825497,
 0.7720204732700163,
 0.49174222323088024,
 0.6153990496874551,
 0.7811566489588155,
 0.7611012449621745,
 0.5762898593314936,
 0.7424460421239125,
 0.859862590633286,
 0.7500321036151224,
 0.7152562784027332,
 0.25496113420736455,
 0.49111933751063386,
 0.5198650790190857,
 0.47488189530192826,
 0.6849153687069056,
 0.5234153433025379,
 0.5093148894997479,
 0.5824511487854842,
 0.6317891523291201,
 0.7754206463621974,
 0.7404223225513304,
 0.7512732093355714,
 0.7567070114450096,
 0.5964867534931837,
 0.7206698022289992,
 0.5307136630782889,
 0.6328829940818645,
 0.5344090573711346,
 0.7349041291263885,
 0.47598748379980804,
 0.6920879068134533,
 0.42926128493507565,
 0.35734898999033116,
 0.6209618988570276,
 0.7903844427735122,
 0.7885603716735061,
 0.6537014363289697,
 0.7212012369164598,
 0.4869261441546944,
 0.6728107272712323,
 0.5995612771890216,
 0.7060103567641174,
 0.44841259803722655,
 0.7198178722326928,
 0.5839207859928561,
 0.5915302399324762,
 0.6305289558472822,
 0.6510754216527836,
 0.7205121207819412,
 0.598665291016552,
 0.6144467900403988,
 0.7400022029955395,
 0.6449485061800675,
 0.7177594227447857,
 0.6455932274593724,
 0.6609949545633209,
 0.6440611633002142,
 0.47221299673182116,
 0.4688683272775436,
 0.5133755468632548,
 0.7557461681855231,
 0.8120251525548169,
 0.6669540126963763,
 0.4966851734253602,
 0.7416179912589438,
 0.5371354064289133,
 0.5743524671944412,
 0.631050409420206,
 0.6122536327812719,
 0.4967438940636033,
 0.7437929057377353,
 0.7318806602409281,
 0.6520091239554202,
 0.7440515919307731,
 0.6403654498698775,
 0.7268611472456143,
 0.6015415176151491,
 0.751838935467749,
 0.856960194390321,
 0.5272205938215135,
 0.5488652692335371,
 0.5914158022229725,
 0.5972091556719685,
 0.5885900844730172,
 0.6536341140716757,
 0.7143014396054579,
 0.8248489668304232,
 0.5226468267464004,
 0.6737077036556061,
 0.564665573157338,
 0.7226439731883549,
 0.596681109448373,
 0.5593815914689699,
 0.7454808537105218,
 0.3430439456781148,
 0.7161351312183588,
 0.7140183167568337,
 0.7079326987725147,
 0.49820631102019397,
 0.5106164186572855,
 0.5710123405326926,
 0.4502087424741059,
 0.8109647091152237,
 0.5740184385577125,
 0.48221212853127404,
 0.6963095180215793,
 0.5901317512065367,
 0.36165175369993585,
 0.8152031403123591,
 0.5890384924982122,
 0.6825440560437677,
 0.5735286428573779,
 0.47553391315186533,
 0.654779112104213,
 0.47092460480781195,
 0.5865819088511426,
 0.6265299605478042,
 0.7470717883812292,
 0.7275118771098612,
 0.45829875444531143,
 0.7215068250898737,
 0.7939562248422822,
 0.8082300337021848,
 0.8276464694504034,
 0.7739302397852288,
 0.49655722389060764,
 0.1819475482719829,
 0.6855389196953088,
 0.5927421148867844,
 0.6749716298934322,
 0.6839354180844879,
 0.6380838839966031,
 0.6041789397106221,
 0.6238169409747509,
 0.6119761813302932,
 0.6062280660597998,
 0.6689179954078653,
 0.6565889185813867,
 0.6639219171287429,
 0.6843771675508439,
 0.5581713724832547,
 0.7108788704284295,
 0.6774257044576689,
 0.7823153991370867,
 0.672574556844207,
 0.7151364909687634,
 0.4646306194236145,
 -0.10222801268986403,
 0.6694265795973862,
 0.46738092395556674,
 0.6292805279437415,
 0.6514692552631458,
 0.5885247649531833,
 0.5807200126456724,
 0.7546600019180756,
 0.6031131607363807,
 0.6151453537132516,
 0.7336548266678425,
 0.5733954186687332,
 0.6797150205250178,
 0.5316975266915793,
 0.5108535704139382,
 0.5936071032470875,
 0.5958437141890077,
 0.6041779560886402,
 0.657005019993327,
 0.47883599518040587,
 0.5839079826214977,
 0.579631925834081,
 0.6631534546938372,
 0.7415676827867058,
 0.6325561501877053,
 0.678155297287408,
 0.49494051634471636,
 0.4423489955540131,
 0.46002892600362444,
 0.7383012816833002,
 0.7011074538608806,
 0.6608557329449984,
 0.6424140275897042,
 0.5011756989640634,
 0.5047469715095279,
 0.5789398991159123,
 0.5520423885306587,
 0.5912057274080222,
 0.8128157073903126,
 0.770409859631058,
 0.8407597760807888,
 0.6919085818566848,
 0.4327315668785917,
 0.5719323432947474,
 0.7087634313005743,
 0.3529016554197142,
 0.5817183783012869,
 0.7557327422954309,
 0.5280321427160493,
 0.7527679423741347,
 0.7824812351307112,
 0.8594616022356885,
 0.7653333601548439,
 0.2724188119608507,
 0.4644063302499163,
 0.3694590675470172,
 0.4317494100900887,
 0.6920244505699393,
 0.6822868704221846,
 0.7685776602686413,
 0.5502774048394832,
 0.5800123742112853,
 0.5526962679015135,
 0.40812132065061335,
 0.7764995119403812,
 0.6698255287929956,
 0.8072450380397587,
 0.7252486341369311,
 0.5009532457492136,
 0.4071794723367701,
 0.6870354016092387,
 0.6163956848001046,
 0.5430185177342383,
 0.4227076000636215,
 0.5725009851863054,
 0.6007908095208943,
 0.7281316085817919,
 0.6401209712679684,
 0.6217299051489594,
 0.532894879566451,
 0.6532025423200152,
 0.6008232327925029,
 0.7635139759882283,
 0.7587514039114367,
 0.565765936681258,
 0.6950660974791096,
 0.6648055534713215,
 0.6627899835992792,
 0.7833734070542393,
 0.47810636399644635,
 0.7778960081633148,
 0.6187484499198836,
 0.4787165041745457,
 0.6116946980182845,
 0.5837992991708325,
 0.5975808173053831,
 0.7670000148197536,
 0.7382197060334998,
 0.8272760504616724,
 0.5009925965713404,
 0.7078187794061497,
 0.6984251668697157,
 0.6689639600434747,
 0.6785754164378723,
 0.7351798595641656,
 0.6625871380679268,
 0.8991168429460843,
 0.573886311037213,
 0.7714987314055327,
 0.6063676558548868,
 0.7417755543619453,
 0.6881760238437844,
 0.5274935451085687,
 0.7158036520545582,
 0.7632044377226926,
 0.6971579888872895,
 0.3692469209826307,
 0.4137158014587581,
 0.5203785602287239,
 0.7201024030435166,
 0.5523163651642391,
 0.4818316044016703,
 0.5607541723295568,
 0.6155670731195804,
 0.5427310891597699,
 0.7677844306635553,
 0.47372335346196304,
 0.5740570501532993,
 0.5626732406234657,
 0.5712116298067038,
 0.7295878612975015,
 0.5682585552221496,
 0.6410929304070001,
 0.5629505931139932,
 0.6123985886090608,
 0.6502474788921406,
 0.632356654102273,
 0.5189726382518003,
 0.712508348757746,
 0.5716413855466063,
 0.4854306920401722,
 0.6664117202680178,
 0.7559655557183055,
 0.532242850293982,
 0.688993769071262,
 0.7274434610973373,
 0.7832642682193701,
 0.6398610153713098,
 0.611330685340123,
 0.6881504580404907,
 0.6421128250003374,
 0.5448748850812295,
 0.4853724680189162,
 0.6441122788105935,
 0.6553534313744992,
 0.6452285269375675,
 0.830453789389259,
 0.42442713142286437,
 0.6681439942143059,
 0.6454274328498503,
 0.6186689818555307,
 0.680324642150883,
 0.685602728370291,
 0.6458388072438087,
 0.655897026911656,
 0.5427224815080322,
 0.44366948052820887,
 0.7102525851194599,
 0.721185424830957,
 0.6635712135816821,
 0.7663133641480515,
 0.4260266561772805,
 0.7273647933663105,
 0.7744501801344323,
 0.7112332412100504,
 0.46701492169587855,
 0.5032788244609676,
 0.6521140265943574,
 0.3705354696142519,
 0.5845617841310597,
 0.6440557545251612,
 0.5841925366386078,
 0.8034826822474026,
 0.7501461269584002,
 0.49142297716437244,
 0.7976084878531233,
 0.6939633810442671,
 0.8445001529359658,
 0.6830914223386272,
 0.6696427999006038,
 0.725065851839296,
 0.4762924593906769,
 0.5262061444740455,
 0.41915393534185585,
 0.7885075098822201,
 0.6611471821496451,
 0.8176394793682521,
 0.5382799206846522,
 0.5887115908256522,
 0.7448320846083346,
 0.545393251981708,
 0.589294851790795,
 0.4953862612988983,
 0.7165243345345309,
 0.5932537986177536,
 0.6501385432921891,
 0.7653676806324179,
 0.43831003593299855,
 0.7428662098795642,
 0.18539982200069616,
 0.5408544056869986,
 0.7031688283509224,
 0.6720930185289472,
 0.6421628828409651,
 0.7067840169489015,
 0.660383617615999,
 0.6532939341008752,
 0.6813256212952861,
 0.7290355610081125,
 0.6059698480585238,
 0.6375614717542352,
 0.7443349316922427,
 0.6507013102054622,
 0.616779349483098,
 0.7138303153768113,
 0.678608109343221,
 0.6372861797733586,
 0.45582380460639804,
 0.6661310259686636,
 0.5584708152453994,
 0.4272818920171625,
 0.770653086730133,
 0.5378123762643485,
 0.7790565796419451,
 0.6322595321031014,
 0.8231942692431737,
 0.7353487530490099,
 0.7879477035878554,
 0.4881522791115416,
 0.7608431796196836,
 0.5330344407995016,
 0.5717599603688817,
 0.5495046179389156,
 0.7428132610547572,
 0.6654085235201185,
 0.6455916487844561,
 0.7980652130828098,
 0.7613141041783422,
 0.768029027097784,
 0.6415451874664461,
 0.7379386206345684,
 0.6433669805865311,
 0.6325193378074432,
 0.7252398285958239,
 0.6277293925635861,
 0.5371177061013898,
 0.7431736409180668,
 0.5961529294410424,
 0.5749414136650257,
 0.672075053195623,
 0.3541624319130321,
 0.40842249945282605,
 0.6670165412848634,
 0.6706966431721361,
 0.7359589308393639,
 0.48774892109004353,
 0.6679050745387314,
 0.8588298852346175,
 0.4232404127613014,
 0.6488975144495397,
 0.4707657855043479,
 0.6513670921523392,
 0.6641656270618186,
 0.5760718812302837,
 0.6260079125402447,
 0.4355991293217699,
 0.25223494641811883,
 0.6216705471041384,
 0.704287594265667,
 0.7108553913120779,
 0.5531540001815134,
 0.6762487259178047,
 0.7342496508787462,
 0.5424040094199312,
 0.689029299572957,
 0.5966343102618928,
 0.8001832461691216,
 0.7433270762416957,
 0.749631947083039,
 0.6547868364271029,
 0.5705245166463708,
 0.5389593952827986,
 0.7673124526251106,
 0.6211637393131426,
 0.4914697221184,
 0.7727570318788824,
 0.6543937674088012,
 0.5186112416819106,
 0.6094438591012897,
 0.5282088124665538,
 0.662054760711678,
 0.5899550336737152,
 0.6685966620534343,
 0.8451462676299878,
 0.6567296160761087,
 0.5970599383160661,
 0.67403321030552,
 0.6871185104189554,
 0.6716220329786138,
 0.6003219601473118,
 0.5312309204359911,
 0.8594759584716998,
 0.6112747012781068,
 0.6667731424937428,
 0.68628072805103,
 0.8456903542999841,
 0.6631950815637933,
 0.7451357523791275,
 0.6402500866354327,
 0.8245028020589926,
 0.7360714772500903,
 0.7350465955115468,
 0.5942016792301862,
 0.6962041733814157,
 0.7593372531456964,
 0.6184203143749003,
 0.6718321999373803,
 0.5621254732338612,
 0.7266149963325292,
 0.45070998014247876,
 0.6376493283371143,
 0.6313083154326158,
 0.8029008315362922,
 0.622179088295095,
 0.6169261973155916,
 0.5118682600208759,
 0.5998414576171638,
 0.7278499246142568,
 0.6692596616761806,
 0.7235311765396457,
 0.5299544698301052,
 0.6987895674851037,
 0.6929325971222918,
 0.6157095997609954,
 0.6845116720893507,
 0.5161502391362256,
 0.7035076762301717,
 0.7381912030942686,
 0.6517092285550554,
 0.4622907140068153,
 0.7249657614392638,
 0.37953959642949364,
 0.6372891881271714,
 0.41281396413015226,
 0.557173215417742,
 0.8106529570807258,
 0.6266867400483449,
 0.8253586186661389,
 0.6076435939578219,
 0.6913602825062743,
 0.4389280571072254,
 0.5432945605538484,
 0.722917159296756,
 0.6192285893991044,
 0.547710273570531,
 0.464082518572273,
 0.7210689874763904,
 0.3581618701083853,
 0.5953134636711421,
 0.62528473445452,
 0.7707995997221099,
 0.612611187561868,
 0.7835768720069852,
 0.6058720190706194,
 0.594605364446785,
 0.7125372372131104,
 0.6091576433909448,
 0.6302817137051882,
 0.7506431074517375,
 0.7485103673556668,
 0.7364917372043124,
 0.6557785934693836,
 0.464486396511554,
 0.5479911801089374,
 0.5372324969885383,
 0.7442741721142294,
 0.43888999396766193,
 0.793341707489198,
 0.41771692816011363,
 0.509471012874252,
 0.8317784272115811,
 0.7535488977146516,
 0.7505002792117255,
 0.7310424841401872,
 0.73748997959151,
 0.6345939110091519,
 0.813139185923968,
 0.7494920289853455,
 0.6618278563082416,
 0.2759017719447707,
 0.5137612019491058,
 0.4000010456930968,
 0.7614704260570961,
 0.4503484455110318,
 0.4842467303143917,
 0.7244640273419982,
 0.7208895110448688,
 0.6634930082648334,
 0.43913931554777097,
 0.7914604983022022,
 0.47427562147743163,
 0.698381799364721,
 0.7445198509238524,
 0.6459238408819428,
 0.42351470611370456,
 0.43998071547228146,
 0.5836651249431553,
 0.6025899885891769,
 0.7267960634573954,
 0.7232092357827831,
 0.43075613474443186,
 0.6321819221934851,
 0.6136270137220803,
 0.527194869299751,
 0.5865295894918814,
 0.6586952511367358,
 0.5480837327217261,
 0.6725568037737444,
 0.8163803775192147,
 0.46244384269139416,
 0.4394706884565627,
 0.4978322235712176,
 0.6438287034321563,
 0.6276752694288694,
 0.5884298201906519,
 0.5985127022527938,
 0.7053056314119998,
 0.6584075011255531,
 0.291511883334549,
 0.6924200847443067,
 0.8736075437895316,
 0.6753440444857259,
 0.7605852552728403,
 0.7172697812578008,
 0.5792094432233198,
 0.6010180606661857,
 0.6040262928814297,
 0.593320275031088,
 0.4050146551663085,
 0.6984977636294333,
 0.669353855873667,
 0.6079886082206623,
 0.7535494550437022,
 0.8004377772600825,
 0.659040668575986,
 0.4264695694812801,
 0.734975548357593,
 0.7600100357380339,
 0.5321569002029877,
 0.8885460354282488,
 0.6513290791657879,
 0.44547378939082316,
 0.6659660971022743,
 0.7004109080043996,
 0.5359445695049161,
 0.7234504724193894,
 0.5240806438295015,
 0.5386846121747495,
 0.5289727984755355,
 0.5433286588519746,
 0.6502404028131605,
 0.7254297816905556,
 0.7249181919350189,
 0.734614805395169,
 0.7478154293749077,
 0.5886696012150957,
 0.6115876176035828,
 0.6784172525864818,
 0.5845779886433828,
 0.661023937556944,
 0.6086661322726545,
 0.4906266041334634,
 0.7997603886117767,
 0.6117553465594576,
 0.7232723360920079,
 0.5225173255330757,
 0.744679186668429,
 0.6589430264895091,
 0.5684422329093932,
 0.6144982483030796,
 0.826254576599589,
 0.6391488864650741,
 0.5597401369648649,
 0.755657370003629,
 0.6299880652227959,
 0.7031910939626649,
 0.6866720484287949,
 0.6674841493867996,
 0.7307203951902328,
 0.7086084270494115,
 0.7220955136178716,
 0.6127049205856838,
 0.7478412612617888,
 0.6737815844467236,
 0.47362730887290927,
 0.7107058426639077,
 0.5648268518416648,
 0.7628594980092902,
 0.535672997082079,
 0.6270456661500563,
 0.6274101624470647,
 0.5599697932965559,
 0.5513038092835851,
 0.3383891315582309,
 0.5873256607717953,
 0.7588448378463029,
 0.7977687922297596,
 0.7920763290360269,
 0.4529469957196065,
 0.7102106450535041,
 0.7795883389713001,
 0.5598188273450793,
 0.4358518391104498,
 0.6618023843465767,
 0.4792643119232647,
 0.6050174128388354,
 0.7074739586276093,
 0.7961403635713025,
 0.6526430805775116,
 0.48767459952626013,
 0.6357936070074661,
 0.666742768054552,
 0.5372881652605291,
 0.7597025739761679,
 0.6250007966674136,
 0.7190900119748719,
 0.796458902903953,
 0.6020486049933689,
 0.5408855659392342,
 0.42499136697669815,
 0.7026197622764061,
 0.5420698550880594,
 0.5492732437811223,
 0.5686257314579182,
 0.7099952563935971,
 0.6087173311710276,
 0.691053974664694,
 0.7334596488809656,
 0.5724324607481766,
 0.6378329893939051,
 0.7464755877586551,
 0.5362674062675651,
 0.4809023033439729,
 0.4152724791113991,
 0.560314100268285,
 0.7073424848062971,
 0.6816484814161452,
 0.7152623783825477,
 0.6634035003549263,
 0.5810524303441822,
 0.4588703373278251,
 0.7087348676232659,
 0.6105094654197614,
 0.5399370140978572,
 0.665271166487989,
 0.720716170339425,
 0.7178906127301636,
 0.5736917861052715,
 0.6935923125139359,
 0.5743956007080702,
 0.6577945645397643,
 0.5983229832511023,
 0.40942710022595985,
 0.7681586764291266,
 0.5144187660705608,
 0.638133676091883,
 0.7637354200107217,
 0.6401790215217251,
 0.507560890115016,
 0.5288513482825781,
 0.6034269748717638,
 0.48885777451863066,
 0.735285958804389,
 0.5820123632506926,
 0.7422197779082798,
 0.7766079132409339,
 0.7114137662558417,
 0.8183541562857615,
 0.6846494802667857,
 0.49823733360541567,
 0.6443041597482071,
 0.5691625838474732,
 0.5077677731231309,
 0.415252098935723,
 0.800481158310612,
 0.7257227974390005,
 0.7605464993826544,
 0.741068415391132,
 0.6527369105510689,
 0.7242363126469273,
 0.7602931920623426,
 0.4754361746564576,
 0.3918373835726634,
 0.6562144454177493,
 0.6173806134137825,
 0.4637509786740919,
 0.688504859172324,
 0.6548918962061434,
 0.7953451280892125,
 0.6893872196929205,
 0.6564016900073149,
 0.8261965204193614,
 0.4112177630549336,
 0.6937657862208988,
 0.5032465336435565,
 0.6073200142820461,
 0.6697964399052958,
 0.5852517559190733,
 0.8306318287934187,
 0.48177977252452475,
 0.6680682347803412,
 0.8372930391719717,
 0.7201128854662499,
 0.5604221401251264,
 0.6876318258411144,
 0.6383472331182586,
 0.6860729995694848,
 0.7208059032844447,
 0.436971531811309,
 0.6760804442526533,
 0.62637485711559,
 0.5738500689250627,
 0.485839160036597,
 0.628467635112302,
 0.45634073761982863,
 0.6541169026268724,
 0.8142988920249169,
 0.5427221263245594,
 0.7106645465778739,
 0.6089931058913083,
 0.6786811689689909,
 0.6060363837234024,
 0.4944375463228513,
 0.6728415774583995,
 0.723109562903316,
 0.8456743387705505,
 0.7274499763998485,
 0.7248990827020952,
 0.6451602715657542,
 0.7486344123252612,
 0.6355833441242607,
 0.6267656067748439,
 0.7651160031182724,
 0.7103659429576403,
 0.732011207922474,
 0.7442485193913164,
 0.6488085451195695,
 0.7018861287970268,
 0.7266964958884753,
 0.6435143501645091,
 0.4491231817733239,
 0.4325457182165917,
 0.7679405485157265,
 0.5133529782432465,
 0.6810123343434269,
 0.6757275557600799,
 0.5442729390165912,
 0.684809459786188,
 0.6215538550147244,
 0.2821355667915042,
 0.6083041413906298,
 0.5630047826795661,
 0.6008857631437046,
 0.6578238776463348,
 0.5899951595220616,
 0.6655666067535877,
 0.7281882157424693,
 0.6423773998735537,
 0.8263362409363251,
 0.7256955734755732,
 0.6762610508169067,
 0.53298937547734,
 0.6941589386499689,
 0.6562347427288259,
 0.7333414568850576,
 0.6259484688408279,
 0.5573567379313871,
 0.7389195453171122,
 0.7673202233399066,
 0.5908622780162305,
 0.42198750296985177,
 0.7594270580951514,
 0.7933821369508786,
 0.5764962196840677,
 0.7843212989869558,
 0.5415528960297467,
 0.6433888111258153,
 0.55791214868591,
 0.5368955273535638,
 0.6584053819904341,
 0.4216532382202993,
 0.6529812011281314,
 0.7496840325724264,
 0.5857195515729443,
 0.8020896956194944,
 0.6774459078571001,
 0.40931121951521565,
 0.8097884546268623,
 0.6636661028615861,
 0.6586338613272996,
 0.7769923134503733,
 0.6583378864201472,
 0.7247515360848655,
 0.7534139126627006,
 0.782386898139361,
 0.5572343369727579,
 0.6108340165502173,
 0.518025451413566,
 0.5963022410910661,
 0.710723221028837,
 0.4473750753108183,
 0.4743133371012249,
 0.7462743208800389,
 0.41432474449113066,
 0.5873476054548663,
 0.7495435814784135,
 0.7823476107658729,
 0.7552603996771416,
 0.6847051896383152,
 0.7672755932308133,
 0.7937564609041833,
 0.5939957880884156,
 0.5381733243275981,
 0.6075475057164663,
 0.4114219316103185,
 0.761333224666874,
 0.5337301009290729,
 0.7140325920310142,
 0.6655964375116312,
 0.594818966421795,
 0.7055038656466743,
 0.6781729140203016,
 0.7722998448170278,
 0.5800175421767277,
 0.6988368065902986,
 0.5496554145232023,
 0.7250946324862335,
 0.7114688373186393,
 0.8261902922165805,
 0.7134204408545493,
 0.42658417814529814,
 0.6140131553218542,
 0.5949212539490152,
 0.7501867586012203,
 0.6145193081009297,
 0.5426778824965043,
 0.7629937930031386,
 0.6479730390951643,

In [262]:
np.argmax(scores)

np.int64(302)

In [263]:
scores[np.argmax(scores)]

0.8991168429460843

## The best model is found at a certain random state

In [265]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(column_trans_df,lr)
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
r2_score(y_test,y_pred)

0.8991168429460843

In [273]:
pd.DataFrame(columns=X_test.columns,data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5))

                  name company  year kms_driven fuel_type
0  Maruti Suzuki Swift  Maruti  2019        100    Petrol

In [268]:
X_test.columns

Index(['name', 'company', 'year', 'kms_driven', 'fuel_type'], dtype='str')

In [269]:
np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).shape

(5,)

In [270]:
np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5)

array([['Maruti Suzuki Swift', 'Maruti', '2019', '100', 'Petrol']],
      dtype='<U21')

## Export the model

In [276]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [278]:
pipe.predict(pd.DataFrame(columns=['name','company','year','kms_driven','fuel_type'],data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5)))

array([456630.40446065])

In [279]:
pipe.steps[0][1].transformers[0][1].categories[0]

array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat Diesel',
       'Chevrolet Beat LS', 'Chevrolet Beat LT', 'Chevrolet Beat PS',
       'Chevrolet Cruze LTZ', 'Chevrolet Enjoy', 'Chevrolet Enjoy 1.4',
       'Chevrolet Sail 1.2', 'Chevrolet Sail UVA', 'Chevrolet Spark',
       'Chevrolet Spark 1.0', 'Chevrolet Spark LS', 'Chevrolet Spark LT',
       'Chevrolet Tavera LS', 'Chevrolet Tavera Neo', 'Datsun GO T',
       'Datsun Go Plus', 'Datsun Redi GO', 'Fiat Linea Emotion',
       'Fiat Petra ELX', 'Fiat Punto Emotion', 'Force Motors Force',
       'Force Motors One', 'Ford EcoSport', 'Ford EcoSport Ambiente',
       'Ford EcoSport Titanium', 'Ford EcoSport Trend',
       'Ford Endeavor 4x4', 'Ford Fiesta', 'Ford Fiesta SXi', 'Ford Figo',
       'Ford Figo Diesel', 'Ford Figo Duratorq', 'Ford Figo Petrol',
       'Ford Fusion 1.4', 'Ford Ikon 1.3', 'Ford Ikon 1.6',
       'Hindustan Motors Ambassador', 'Honda Accord', 'Honda Amaze',
       'Honda Amaze 1.2', 'Honda Amaze 1.5', 'Honda Brio', 'Honda Brio V',
       'Honda Brio VX', 'Honda City', 'Honda City 1.5', 'Honda City SV',
       'Honda City VX', 'Honda City ZX', 'Honda Jazz S', 'Honda Jazz VX',
       'Honda Mobilio', 'Honda Mobilio S', 'Honda WR V', 'Hyundai Accent',
       'Hyundai Accent Executive', 'Hyundai Accent GLE',
       'Hyundai Accent GLX', 'Hyundai Creta', 'Hyundai Creta 1.6',
       'Hyundai Elantra 1.8', 'Hyundai Elantra SX', 'Hyundai Elite i20',
       'Hyundai Eon', 'Hyundai Eon D', 'Hyundai Eon Era',
       'Hyundai Eon Magna', 'Hyundai Eon Sportz', 'Hyundai Fluidic Verna',
       'Hyundai Getz', 'Hyundai Getz GLE', 'Hyundai Getz Prime',
       'Hyundai Grand i10', 'Hyundai Santro', 'Hyundai Santro AE',
       'Hyundai Santro Xing', 'Hyundai Sonata Transform', 'Hyundai Verna',
       'Hyundai Verna 1.4', 'Hyundai Verna 1.6', 'Hyundai Verna Fluidic',
       'Hyundai Verna Transform', 'Hyundai Verna VGT',
       'Hyundai Xcent Base', 'Hyundai Xcent SX', 'Hyundai i10',
       'Hyundai i10 Era', 'Hyundai i10 Magna', 'Hyundai i10 Sportz',
       'Hyundai i20', 'Hyundai i20 Active', 'Hyundai i20 Asta',
       'Hyundai i20 Magna', 'Hyundai i20 Select', 'Hyundai i20 Sportz',
       'Jaguar XE XE', 'Jaguar XF 2.2', 'Jeep Wrangler Unlimited',
       'Land Rover Freelander', 'Mahindra Bolero DI',
       'Mahindra Bolero Power', 'Mahindra Bolero SLE',
       'Mahindra Jeep CL550', 'Mahindra Jeep MM', 'Mahindra KUV100',
       'Mahindra KUV100 K8', 'Mahindra Logan', 'Mahindra Logan Diesel',
       'Mahindra Quanto C4', 'Mahindra Quanto C8', 'Mahindra Scorpio',
       'Mahindra Scorpio 2.6', 'Mahindra Scorpio LX',
       'Mahindra Scorpio S10', 'Mahindra Scorpio S4',
       'Mahindra Scorpio SLE', 'Mahindra Scorpio SLX',
       'Mahindra Scorpio VLX', 'Mahindra Scorpio Vlx',
       'Mahindra Scorpio W', 'Mahindra TUV300 T4', 'Mahindra TUV300 T8',
       'Mahindra Thar CRDe', 'Mahindra XUV500', 'Mahindra XUV500 W10',
       'Mahindra XUV500 W6', 'Mahindra XUV500 W8', 'Mahindra Xylo D2',
       'Mahindra Xylo E4', 'Mahindra Xylo E8', 'Maruti Suzuki 800',
       'Maruti Suzuki A', 'Maruti Suzuki Alto', 'Maruti Suzuki Baleno',
       'Maruti Suzuki Celerio', 'Maruti Suzuki Ciaz',
       'Maruti Suzuki Dzire', 'Maruti Suzuki Eeco',
       'Maruti Suzuki Ertiga', 'Maruti Suzuki Esteem',
       'Maruti Suzuki Estilo', 'Maruti Suzuki Maruti',
       'Maruti Suzuki Omni', 'Maruti Suzuki Ritz', 'Maruti Suzuki S',
       'Maruti Suzuki SX4', 'Maruti Suzuki Stingray',
       'Maruti Suzuki Swift', 'Maruti Suzuki Versa',
       'Maruti Suzuki Vitara', 'Maruti Suzuki Wagon', 'Maruti Suzuki Zen',
       'Mercedes Benz A', 'Mercedes Benz B', 'Mercedes Benz C',
       'Mercedes Benz GLA', 'Mini Cooper S', 'Mitsubishi Lancer 1.8',
       'Mitsubishi Pajero Sport', 'Nissan Micra XL', 'Nissan Micra XV',
       'Nissan Sunny', 'Nissan Sunny XL', 'Nissan Terrano XL',
       'Nissan X Trail', 'Renault Duster', 'Renault Duster 110',
       'Renault Duster 110PS', 'Renault Duster 85', 'Renault Duster 85PS',
       'Renault Duster RxL', 'Renault Kwid', 'Renault Kwid 1.0',
       'Renault Kwid RXT', 'Renault Lodgy 85', 'Renault Scala RxL',
       'Skoda Fabia', 'Skoda Fabia 1.2L', 'Skoda Fabia Classic',
       'Skoda Laura', 'Skoda Octavia Classic', 'Skoda Rapid Elegance',
       'Skoda Superb 1.8', 'Skoda Yeti Ambition', 'Tata Aria Pleasure',
       'Tata Bolt XM', 'Tata Indica', 'Tata Indica V2', 'Tata Indica eV2',
       'Tata Indigo CS', 'Tata Indigo LS', 'Tata Indigo LX',
       'Tata Indigo Marina', 'Tata Indigo eCS', 'Tata Manza',
       'Tata Manza Aqua', 'Tata Manza Aura', 'Tata Manza ELAN',
       'Tata Nano', 'Tata Nano Cx', 'Tata Nano GenX', 'Tata Nano LX',
       'Tata Nano Lx', 'Tata Sumo Gold', 'Tata Sumo Grande',
       'Tata Sumo Victa', 'Tata Tiago Revotorq', 'Tata Tiago Revotron',
       'Tata Tigor Revotron', 'Tata Venture EX', 'Tata Vista Quadrajet',
       'Tata Zest Quadrajet', 'Tata Zest XE', 'Tata Zest XM',
       'Toyota Corolla', 'Toyota Corolla Altis', 'Toyota Corolla H2',
       'Toyota Etios', 'Toyota Etios G', 'Toyota Etios GD',
       'Toyota Etios Liva', 'Toyota Fortuner', 'Toyota Fortuner 3.0',
       'Toyota Innova 2.0', 'Toyota Innova 2.5', 'Toyota Qualis',
       'Volkswagen Jetta Comfortline', 'Volkswagen Jetta Highline',
       'Volkswagen Passat Diesel', 'Volkswagen Polo',
       'Volkswagen Polo Comfortline', 'Volkswagen Polo Highline',
       'Volkswagen Polo Highline1.2L', 'Volkswagen Polo Trendline',
       'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
       'Volkswagen Vento Konekt', 'Volvo S80 Summum'], dtype=object)